# Generated by Django 5.2.7 on 2025-11-20 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulp_fiction', '0003_author_created_by_book_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='book',
            name='book_name_author_idx',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('name', 'created_by')},
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('name', 'author', 'created_by')},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['name', 'author', 'created_by'], name='book_name_creator_author_idx'),
        ),
    ]
